# Generated by Django 4.2.4 on 2023-08-31 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(help_text='Moshina nomi', max_length=15)),
                ('adreess', models.CharField(help_text='Manzil', max_length=20)),
                ('made_date', models.DateField(help_text='Ishlab chiqarilgan sana', max_length=20)),
                ('made_in', models.CharField(help_text='Ishlab chiqarilgan joy', max_length=20)),
                ('probeg', models.FloatField(help_text='Probeg', max_length=20)),
                ('colour', models.CharField(help_text='Moshina ranggi', max_length=20)),
                ('added_date', models.DateTimeField(help_text='Qoshilgan sana', max_length=20)),
                ('author_name', models.CharField(help_text='Moshina egasi', max_length=20)),
                ('description', models.TextField(help_text='Moshina tavsifi', max_length=20)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
            ],
        ),
    ]
